// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ComputePowerIndexAdapter
std::vector<std::string> ComputePowerIndexAdapter(Rcpp::String index, Rcpp::Nullable<Rcpp::NumericVector> weights, double quota, Rcpp::String weightsfile, Rcpp::Nullable<Rcpp::List> precoalitions, bool filterNullPlayers, bool verbose, bool weightedMajorityGame, bool inputFloatWeights);
RcppExport SEXP _EfficientPowerIndices_ComputePowerIndexAdapter(SEXP indexSEXP, SEXP weightsSEXP, SEXP quotaSEXP, SEXP weightsfileSEXP, SEXP precoalitionsSEXP, SEXP filterNullPlayersSEXP, SEXP verboseSEXP, SEXP weightedMajorityGameSEXP, SEXP inputFloatWeightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type index(indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type quota(quotaSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type weightsfile(weightsfileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type precoalitions(precoalitionsSEXP);
    Rcpp::traits::input_parameter< bool >::type filterNullPlayers(filterNullPlayersSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type weightedMajorityGame(weightedMajorityGameSEXP);
    Rcpp::traits::input_parameter< bool >::type inputFloatWeights(inputFloatWeightsSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputePowerIndexAdapter(index, weights, quota, weightsfile, precoalitions, filterNullPlayers, verbose, weightedMajorityGame, inputFloatWeights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EfficientPowerIndices_ComputePowerIndexAdapter", (DL_FUNC) &_EfficientPowerIndices_ComputePowerIndexAdapter, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_EfficientPowerIndices(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
