# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputePowerIndex <- function(index, weights, quota, filterNullPlayers = FALSE, verbose = FALSE, weightedMajorityGame = FALSE) {
    .Call(`_EfficientPowerIndices_ComputePowerIndex`, index, weights, quota, filterNullPlayers, verbose, weightedMajorityGame)
}

